name: "\U0001F30F Environment"
description: "ì¶”ê°€ì ì¸ í™˜ê²½ì„¤ì •ì´ í•„ìš”í•œê°€ìš”?"
labels: "\U0001F30F Environment"
body:
  - type: textarea
    attributes:
      label: ğŸ¤” ì„¤ëª…
      description: í˜„ì¬ ì–´ë–¤ ìƒí™©ì¸ì§€ ì„¤ëª…í•´ ì£¼ì„¸ìš”.
      placeholder: ìì„¸íˆ ì ì„ìˆ˜ë¡ ì¢‹ìŠµë‹ˆë‹¤!
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… ì‘ì—…í•  ë‚´ìš©
      description: ì¶”ê°€í•  í™˜ê²½ì„¤ì •ì— ëŒ€í•´ ê°„ëµíˆ ê¸°ë¡í•´ ì£¼ì„¸ìš”.
      placeholder: ìµœëŒ€í•œ ì„¸ë¶„í™” í•´ì„œ ì ì–´ì£¼ì„¸ìš”!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ™‹ğŸ» ì°¸ê³  ìë£Œ
      description: ì¶”ê°€ì ì¸ í™˜ê²½ì„¤ì •ì— ëŒ€í•œ ì°¸ê³  ìë£Œê°€ ìˆë‹¤ë©´ ì‘ì„±í•´ ì£¼ì„¸ìš”.
  - type: textarea
    attributes:
      label: â° ì¶”ì • ì‹œê°„
      description: í™˜ê²½ì„¤ì •ì„ ì¶”ê°€í•˜ê¸° ìœ„í•œ ì¶”ì • ì‹œê°„ì— ëŒ€í•´ ì‘ì„±í•´ì£¼ì„¸ìš”.
    validations:
      required: true
  - type: textarea
    attributes:
      label: â° ì†Œìš” ì‹œê°„
      description: í™˜ê²½ì„¤ì • ì¶”ê°€ ì†Œìš” ì‹œê°„ì— ëŒ€í•´ ì‘ì„±í•´ì£¼ì„¸ìš”.
    validations:
      required: true
